-- AlterTable
ALTER TABLE "area" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "avenue" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "district" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "impasse" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "lane" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "organization" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "organization_version" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "passage" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "residential_area" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "street" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);

-- AlterTable
ALTER TABLE "village" ALTER COLUMN "index" SET DATA TYPE VARCHAR(1000);
